server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://backend.localhelp.store:8080;
        proxy_http_version 1.1;
    }

    location /health {
        stub_status on;
        access_log off;
    }
}